### ISSUE TITLE
Can't @ target myself with notifications (space in handle)

### ISSUE THREAD

**Issue by mishterk** [a-sync/slackr#1]
Hi there,

Great little script – super handy. The only issue I'm having is posting a message to myself. My @ handle it @Phil Kurth and when I try that or '@Phil Kurth' or @Phil\ Kurth, I get a `channel_not_found` response. 

Any thoughts on how I might get things posting in a direct message?

Cheers,
Phil

**Comment by a-sync** [comment]
Hi,
could you show what exact command you use?
`slackr -r "@phil Kurth" test123` should work, but never really tested with a handle with a space in it.

**Comment by a-sync** [comment]
Ok, after testing this on a clean new slack sub, it turns out the new `@handles with spaces` format does not work with webhooks.
I also noticed that the handle (display name) was not required to set directly, and the default was set to `@slack1`. I changed that first to something with space, then removed it (since it's optional) and set a full name with a space in it. 

The result with the provided curl post example from the webhooks integration page:
```
$ curl -X POST --data-urlencode "payload={\"channel\": \"@A. Name\", \"username\": \"webhookbot\", \"text\": \"This is posted to @A. Name and comes from a bot named webhookbot.\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/XXX/YYY/ZZZ
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   274  100    17  100   257     32    484 --:--:-- --:--:-- --:--:--   532
channel_not_found
```
When i checked the webhook's settings i noticed that `@slack1` was still available, and setting it as the channel property for the message still works.
![unknown-slack-handle](https://user-images.githubusercontent.com/14183614/34074871-a6b937ca-e2b8-11e7-8657-37a3eecd90a8.png)

This might just be something undocumented, but i couldn't find anything about this, or where this can be changed.

I contacted slack support about this, and will update here when it's answered.
For now as i see you have two options: set a display name without a space (or other special char), or check the integration channel settings to see what is your "old" type handle.

**Comment by mishterk** [comment]
Howdy,

Thanks for digging into this. Checking the integration, as you suggested, gave me the correct @handle and the notification is now working. 

Cheers!
Phil

**Comment by a-sync** [comment]
Np. Depending on the response from slack support, i might create a wiki page later.
Closing this for now.
:wave:

**Comment by a-sync** [comment]
Hi, 
just here to follow up on this.
Slack support was very kind and made it clear, that the recent changes to user name / display name are the first steps in phasing out @username which can be found / changed here: https://my.slack.com/account/settings#username

It is recommended to use a slack "channel-like id" as recipient to make it future proof.
I put all the important details on the wiki page here: https://github.com/a-sync/slackr/wiki#important

![recipient-types](https://user-images.githubusercontent.com/14183614/34314963-3f4b2de8-e77a-11e7-8c90-4bd750d37c25.jpg)

gl
