### ISSUE TITLE
Channel override is not working

### ISSUE THREAD

**Issue by alokinac** [a-sync/slackr#3]
Hello,

Whatever the channel I indicate, the message will be sent to the channel chosen when the Slack Webhook App was created. For instance:

slackr -w "https://hooks.slack.com/services/MY/WEBHOOK/URL" -r "#newtest" test_message

will post the message in #general channel because the webhook URL was created for the #general channel. Of course #newtest exists...

**Comment by a-sync** [comment]
Hi there.
Please try with `-r newtest` (without #).
This also might be a permission issue. The created hook can have some fixed configuration.  
Another thing you should try, is using the slack channel like ID for that channel. (eg.: `-r C012345`)  
More info here: https://github.com/a-sync/slackr/wiki

**Comment by alokinac** [comment]
Hello,

Thanks for the feedback! I've tried the channel name without a # as well as the channel ID, but the result is exactly the same. It does seem to me that it's a permission issue indeed... While creating the webhook, the Channel is mandatory, so I'm thinking that maybe Slack has changed something and it's not possible to post to a channel which is not associated with the webhook... Do you think that's possible? When using API, everything works fine.

**Comment by a-sync** [comment]
Checked, and it still works for me.  
I think the app/integration hook used might not be allowed to interact with that channel. You should contact an admin on that channel or the slack support team to get more details on the issue.  

I'm closing this since it seems this is not a slackr issue.
Please feel free to share any upcoming details about the problem/solution or reopen.
